version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: n88szWB0PwX6lnHxowfQ
      MONGO_INITDB_DATABASE: chatgpt
